In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset=pd.read_csv('./diabetes.csv')

In [3]:
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [4]:
x=dataset.iloc[:,0:8].values
y=dataset.iloc[:,8].values

In [5]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [6]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [8]:
x_test

array([[  1.   , 199.   ,  76.   , ...,  42.9  ,   1.394,  22.   ],
       [  2.   , 107.   ,  74.   , ...,  33.6  ,   0.404,  23.   ],
       [  4.   ,  76.   ,  62.   , ...,  34.   ,   0.391,  25.   ],
       ...,
       [  1.   , 109.   ,  60.   , ...,  25.4  ,   0.947,  21.   ],
       [  3.   , 128.   ,  78.   , ...,  21.1  ,   0.268,  55.   ],
       [  5.   ,  88.   ,  78.   , ...,  27.6  ,   0.258,  37.   ]])

In [9]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)

x_test=sc.transform(x_test)



In [11]:
from sklearn.neighbors import KNeighborsClassifier
#p-> 2 for euclidean , 1 for manhattan, metric="minkowski" implies both euclidean and manhattan can be applied
#module pickle is for serialising the object into byte stream
classifier= KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [12]:
y_pred=classifier.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8020833333333334


In [14]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
y_pred=classifier.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred)) #without scaling->80.7, with scaling->80.2

0.8020833333333334


In [17]:
df=pd.read_csv('./advertising.csv')

In [18]:
df

Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                       68.95   35     61833.90                256.09   
1                       80.23   31     68441.85                193.77   
2                       69.47   26     59785.94                236.50   
3                       74.15   29     54806.18                245.89   
4                       68.37   35     73889.99                225.58   
5                       59.99   23     59761.56                226.74   
6                       88.91   33     53852.85                208.36   
7                       66.00   48     24593.33                131.76   
8                       74.53   30     68862.00                221.51   
9                       69.88   20     55642.32                183.82   
10                      47.64   49     45632.51                122.02   
11                      83.07   37     62491.01                230.87   
12                      69.57   48     51636.92                113.12   
13                      79.52   24     51739.63                214.23   
14                      42.95   33     30976.00                143.56   
15                      63.45   23     52182.23                140.64   
16                      55.39   37     23936.86                129.41   
17                      82.03   41     71511.08                187.53   
18                      54.70   36     31087.54                118.39   
19                      74.58   40     23821.72                135.51   
20                      77.22   30     64802.33                224.44   
21                      84.59   35     60015.57                226.54   
22                      41.49   52     32635.70                164.83   
23                      87.29   36     61628.72                209.93   
24                      41.39   41     68962.32                167.22   
25                      78.74   28     64828.00                204.79   
26                      48.53   28     38067.08                134.14   
27                      51.95   52     58295.82                129.23   
28                      70.20   34     32708.94                119.20   
29                      76.02   22     46179.97                209.82   
..                        ...  ...          ...                   ...   
970                     40.18   29     50760.23                151.96   
971                     45.17   48     34418.09                132.07   
972                     50.48   50     20592.99                162.43   
973                     80.87   28     63528.80                203.30   
974                     41.88   40     44217.68                126.11   
975                     39.87   48     47929.83                139.34   
976                     61.84   45     46024.29                105.63   
977                     54.97   31     51900.03                116.38   
978                     71.40   30     72188.90                166.31   
979                     70.29   31     56974.51                254.65   
980                     67.26   57     25682.65                168.41   
981                     76.58   46     41884.64                258.26   
982                     54.37   38     72196.29                140.77   
983                     82.79   32     54429.17                234.81   
984                     66.47   31     58037.66                256.39   
985                     72.88   44     64011.26                125.12   
986                     76.44   28     59967.19                232.68   
987                     63.37   43     43155.19                105.04   
988                     89.71   48     51501.38                204.40   
989                     70.96   31     55187.85                256.40   
990                     35.79   44     33813.08                165.62   
991                     38.96   38     36497.22                140.67   
992                     69.17   40     66193.81                

In [21]:
a=df.iloc[:,0:8].values
b=df.iloc[:,9].values

In [22]:
a

array([[68.95, 35, 61833.9, ..., 'Wrightburgh', 0, 'Tunisia'],
       [80.23, 31, 68441.85, ..., 'West Jodi', 1, 'Nauru'],
       [69.47, 26, 59785.94, ..., 'Davidton', 0, 'San Marino'],
       ...,
       [51.63, 51, 42415.72, ..., 'South Jessica', 1, 'Mongolia'],
       [55.55, 19, 41920.79, ..., 'West Steven', 0, 'Guatemala'],
       [45.01, 26, 29875.8, ..., 'Ronniemouth', 0, 'Brazil']],
      dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
a[:,4]=labelencoder_x.fit_transform(a[:,4])
a[:,5]=labelencoder_x.fit_transform(a[:,5])
a[:,7]=labelencoder_x.fit_transform(a[:,7])

In [24]:
a

array([[68.95, 35, 61833.9, ..., 961, 0, 215],
       [80.23, 31, 68441.85, ..., 903, 1, 147],
       [69.47, 26, 59785.94, ..., 111, 0, 184],
       ...,
       [51.63, 51, 42415.72, ..., 798, 1, 140],
       [55.55, 19, 41920.79, ..., 935, 0, 85],
       [45.01, 26, 29875.8, ..., 744, 0, 28]], dtype=object)

In [25]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features=[0])
a=onehotencoder.fit_transform(a).toarray()

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [26]:
a

array([[  0.,   0.,   0., ..., 961.,   0., 215.],
       [  0.,   0.,   0., ..., 903.,   1., 147.],
       [  0.,   0.,   0., ..., 111.,   0., 184.],
       ...,
       [  0.,   0.,   0., ..., 798.,   1., 140.],
       [  0.,   0.,   0., ..., 935.,   0.,  85.],
       [  0.,   0.,   0., ..., 744.,   0.,  28.]])

In [27]:
from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.25,random_state=0)

In [31]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(a_train,b_train)

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [32]:
b_pred=classifier.predict(a_test)

In [33]:
from sklearn.metrics import accuracy_score
print(accuracy_score(b_test,b_pred))

0.924
